spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud_web_demo
    username: nativeuser
    password: PmDbS@787
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    view:
      prefix: /WEB-INF/jsps/
      suffix: .jsp
  mail:
    host: smtp.gmail.com
    username: mohamad.aslam.0864@gmail.com
    password: elephant_59
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
            starttls:
              enable: true
            ssl:
              enable: true
server:
  servlet:
    context-path: /locationWeb